### ISSUE TITLE
Issue with napari v0.2.2

### ISSUE THREAD

**Issue by mrakitin** [nsls-ii-forge/napari-feedstock#2]
Encountered an issue:
```py
mrakitin@xf18id-ws4:~$ conda activate collection-2020-2.0rc5
(/opt/conda_envs/collection-2020-2.0rc5) mrakitin@xf18id-ws4:~$
(/opt/conda_envs/collection-2020-2.0rc5) mrakitin@xf18id-ws4:~$
(/opt/conda_envs/collection-2020-2.0rc5) mrakitin@xf18id-ws4:~$ napari
/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/napari/__init__.py:27: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

  warn(message=warn_message)
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mrakitin'
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2020-2.0rc5/bin/napari", line 11, in <module>
    sys.exit(main())
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/napari/__main__.py", line 54, in main
    v = Viewer()
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/napari/viewer.py", line 23, in __init__
    qt_viewer = QtViewer(self)
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/napari/_qt/qt_viewer.py", line 65, in __init__
    self.console = QtConsole({'viewer': self.viewer})
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/napari/_qt/qt_console.py", line 45, in __init__
    kernel_client.start_channels()
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/qtconsole/kernel_mixins.py", line 47, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/ipykernel/inprocess/client.py", line 64, in start_channels
    super(InProcessKernelClient, self).start_channels()
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/jupyter_client/client.py", line 118, in start_channels
    self.control_channel.start()
  File "/opt/conda_envs/collection-2020-2.0rc5/lib/python3.7/site-packages/jupyter_client/client.py", line 200, in control_channel
    socket, self.session, self.ioloop
TypeError: ChannelABC() takes no arguments
```
Will try to build the newest version and try again.

**Comment by mrakitin** [comment]
Newer versions do not have such issues (see e.g. #5).
